/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.ac.iie.zoope.server;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-04-09")
public enum ActionType implements org.apache.thrift.TEnum {
  INSERT(0),
  SEARCH(1),
  DELETE(2),
  UPDATE(3);

  private final int value;

  private ActionType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ActionType findByValue(int value) { 
    switch (value) {
      case 0:
        return INSERT;
      case 1:
        return SEARCH;
      case 2:
        return DELETE;
      case 3:
        return UPDATE;
      default:
        return null;
    }
  }
}
